### ISSUE TITLE
Listing 1.6: Roots of a polynomial in PDF file has a typo.

### ISSUE THREAD

**Issue by liuifan** [h-Klok/StatsWithJuliaBook#1]
On page 17 of the pdf file, the root of the function should actually be -0.2 and 0.5  .

**Comment by liuifan** [comment]
ohh, it is not a book typo.
The error is in line 11 of the code of Listing 1.6.
Change `polynomial = polynomialGenerator(-10,3,1) ` to `（1，3，-10）`

**Comment by h-Klok** [comment]
Good find thank you! I've updated the code and fixed the output below listing 1.6. The PDF will reflect these changes on the next release.
