### ISSUE TITLE
Add examples with DifferentialEquations.jl when doing dynamics?

### ISSUE THREAD

**Issue by ChrisRackauckas** [h-Klok/StatsWithJuliaBook#15]
When showing the ODEs, SDEs, and discrete event simulation, it would be nice to showcase how to use the packages, since writing out Euler methods and using Kalman filters really doesn't scale. This would make it useful to the wider community of engineers.

**Comment by yoninazarathy** [comment]
We do this in [Listing 10.2](https://github.com/h-Klok/StatsWithJuliaBook/blob/master/10_chapter/springMass.jl) already. Indeed DifferentialEquations.jl is a very useful package.
