### ISSUE TITLE
BibTex for this book

### ISSUE THREAD

**Issue by JiaxiangBU** [h-Klok/StatsWithJuliaBook#16]
Thanks for your excellent work. I plan to cite this project and the related book into a talk and tutorial. I write a Bibtex and think it is helpful for other users who have the same purpose as me.

```BibTeX
@online{Klok2019,
  author = {Hayden Klok and Yoni Nazarathy},
  title = {Statistics with Julia},
  subtitle = {Fundamentals for Data Science, Machine Learning and Artificial Intelligence.},
  year = 2019,
  url = {https://people.smp.uq.edu.au/YoniNazarathy/julia-stats/StatisticsWithJulia.pdf},
  urldate = {2019-07-14}
}
```

**Comment by yoninazarathy** [comment]
Thank you JiaxiangBU. The book has a contract with Springer and will be published via Springer. The online version will be removed (however code will remain available) once published. In your Bibtex entry, maybe just remove "howpublished".

**Comment by JiaxiangBU** [comment]
> In your Bibtex entry, maybe just remove "howpublished".

Just wait for this published one and I drop this entry in the issue body.
