### ISSUE TITLE
Page 184 Typo Eq 5.3

### ISSUE THREAD

**Issue by dmetivie** [h-Klok/StatsWithJuliaBook#28]
Hello,
Thank so much for your work!

I think there is a typo in eq 5.3, the third nonzero case of the joint PMF of \bar{X} and S^2 should be "$\bar{x} = 1$ and $s^2 = 0$." and not "$\bar{x} = 1$ and $s^2 = 1$."

**Comment by yoninazarathy** [comment]
Thank you. This just made it into the production version. Great catch.
