### ISSUE TITLE
Warnings in `plotSimple.jl`

### ISSUE THREAD

**Issue by sbacelar** [h-Klok/StatsWithJuliaBook#4]
When running `plotSimple.jl`I get several warnings like this one (that I don't understand completely):
```
┌ Warning: `getindex(o::PyObject, s::Symbol)` is deprecated in favor of dot overloading (`getproperty`) so elements should now be accessed as e.g. `o.s` instead of `o[:s]`.
│   caller = top-level scope at In[1]:8
└ @ Core In[1]:8
```

**Comment by h-Klok** [comment]
Thanks @sbacelar, those errors had to do with how python object fields/attributes were referenced, they should now be fixed.
