### ISSUE TITLE
Section 1.2, REPL Command Line Interface typo

### ISSUE THREAD

**Issue by VincentTam** [h-Klok/StatsWithJuliaBook#5]
> It can <del>can</del> be downloaded directly from: https://julialang.org/downloads/.

**Comment by VincentTam** [comment]
Sorry for another message.  This typo still appears in the current version of the PDF.  Perhaps a screenshot would be helpful for spotting out the error.

![book typo](https://user-images.githubusercontent.com/5748535/57447673-e159f100-7257-11e9-8185-975adcbc0a9a.png)

**Comment by h-Klok** [comment]
Thanks Vincent, it should now be fixed for future draft releases.
