### ISSUE TITLE
License of the code samples

### ISSUE THREAD

**Issue by VincentTam** [h-Klok/StatsWithJuliaBook#6]
Thanks for your great book.  I wished that it had appeared two years ago.

To learn programming in Julia, the most efficient way is to get my hands dirty and play with existing code.  As a result, I've created [a fork on Framagit](https://framagit.org/VincentTam/StatsWithJuliaBook) for personal learning a few weeks ago.  That would mean that I'm "redistribuing modified versions" of your code.

Having a license for your code would allow others to choose the optimal way of storing the cloned Git repo for this project.

**Comment by yoninazarathy** [comment]
Thanks. Has MIT License now.
