### ISSUE TITLE
Add project and manifest TOML files

### ISSUE THREAD

**Issue by VincentTam** [h-Klok/StatsWithJuliaBook#7]
> If you commit the project and manifest files in version control, you'll have a perfect record of your entire Julia dependency graph for each project.  
> --- [*Is any way to install multiple versions of same package?*](https://discourse.julialang.org/t/is-any-way-to-install-multiple-versions-of-same-package/20898/5?u=vincenttam) on Julia Discourse by StefanKarpinski

These TOML files would tell us the version of packages used in this book.  They will facilitate the debug process and discussions in case of bugs/warnings, say in #4.

```julia
julia> # press `]` to activate the package REPL mode...
(v1.1) pkg> activate .
(Project1) pkg> add {package-name}@{version-number}
```

**Comment by yoninazarathy** [comment]
Done. Thank you.
